services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 2345:5432
    volumes:
      - data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payload-tmdb-movies

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - '71072:27017'
  #   command:
  #     - --storageEngine=wiredTiger
  #   volumes:
  #     - data:/data/db
  #   logging:
  #     driver: none

  adminer:
    image: adminer
    restart: always
    ports:
      - 2345:5432
      # - '71072:27017'

volumes:
  data:
